theme: jekyll-theme-cayman
layout: page
title: "Matchoudi's Capstone"
permalink: https://github.com/LionRouge1/capstone_M1/tree/capstone_Br
lsi: false
safe: true
source: [https://github.com/LionRouge1/capstone_M1/tree/capstone_Br]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

